services:
  aerostack2:
    image: aerostack2_sim
    container_name: aerial_sim_cont
    network_mode: host
    ipc: host
    tty: true
    privileged: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/root/.Xauthority # Change from /tmp/.Xauthority to /root/.Xauthority
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./urdf_serving/cors_mesh_server.py:/root/cors_mesh_server.py
      - ./urdf_serving/sdf_to_urdf_publisher.py:/root/sdf_to_urdf_publisher.py
      - ./simulation:/root/simulator/simulation
      - ./drone_joy_control:/root/aerostack2_ws/src/drone_joy_control
      - /etc/sysctl.d:/etc/sysctl.d
      - /dev/shm:/dev/shm
    devices:
      - /dev/input/js0:/dev/input/js0 # For joystick access
      - /dev/input/event*:/dev/input/event* # Additional input devices

